#quarkus.log.level=DEBUG
#quarkus.log.category."io.quarkus".level=DEBUG

# Quarkus Konfiguration für H2 (Datenbank im Dateimodus)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/mydb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate ORM Konfiguration
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
